# -*- coding: utf-8 -*-
"""Python_internal_assesment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DgMnmByVEO5taVhMpdd2JfHt9gwrOS_c
"""

#1
l=float(input("Enter the length of the rectangle:"))
b=float(input("Enter the breadth of the rectangle:"))
a=round(l*b,2)
print("The area of rectangle is",a)

#2
weight=float(input('enter the weight in kg:'))
height=float(input('enter the height in m:'))
bmi=weight/(height**2)
print("your bmi is :",round(bmi,2))

#3
students_scores={}
while 1:
  n=input("do you want to enter the data y/n:")
  if(n.lower()=='y'):
    name=input("enter students name:")
    scores=input("enter students score")
    students_scores[name]=scores
  else:
    break
print(students_scores)

#4
age = float(input("enter user age in years"))
if(age<18):
  print("user is minor")
elif(age>18 and age<60):
  print("user is adult")
else:
  print("user is senior")

#5
for i in range(1,50):
  if(i%2==0):
    print(i)

#6
while 1:
  n=input("enter your password:")
  if (n=='password'):#here i have assumed the correct password is "password".
    break
  else:
    input("enter your correct password:")

#7
def avg(n):
  avg=0
  a=len(n)
  for i in range(0,len(n)):
    avg=(avg+n[i])/a
  print("Average of given list is ",avg)

my_list = []
n=int(input("number of elements in list:"))
for i in range(0,n):
  element = int(input("Enter an element: "))
  my_list.append(element)
print(my_list)

avg(my_list)

#8

def vowel_checker(n):
  count=0
  for i in range(1,len(n)):
    if(n[i] in ['a','e','i','o','u']):
      count=count+1
  print("total number of vowels is:",count)

n=input("enter the string:")
vowel_checker(n)

#10
try:
  n=int(input("enter number 1:"))
  o=input("enter number 2:")
  add=n+o
  print(add)
except:
  print("Your input is non numeric")

#11
try:
  n=int(input("enter a value"))
  print(n)
except:
  print("entered value is not integer")

#12
try:
  n=int(input("enter numerator:"))
  d=int(input("enter denominator:"))
  div=n/d
  print(div)
except:
      print("Division by zero error")

#13
file_2=open('/content/sample.txt','w')
file_2.write("hello python")
print("the given value is written")
file_2.close()

#14
file_3=open('/content/sample.txt','r')
print(file_3.read())
file_3.close()

#15
file_4=open('/content/sample.txt','w')
file_4.write("hiii hello")
print("new line is appended")
file_4.close()