# -*- coding: utf-8 -*-
"""LVADSUSR91-JAYAPRIYAA-FA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUxOFFJ3zqZTANiYPLqtYA90gkWz9IeT
"""

import pandas as pd
import numpy as np
import seaborn as sns

#1 Load dataset
df=pd.read_csv('/content/Walmart_Dataset Python_Final_Assessment.csv')
df.head()
df.info()

#2 Data cleaning Null values
print(df.isnull().sum())# there are no null values
print('total duplicated rows:',df.duplicated().sum())#returns the total number of duplicated rows

df['Order Date']=pd.to_datetime(df['Order Date'])
df['Ship Date']=pd.to_datetime(df['Ship Date'])

#3 Descriptive analysis
df.describe()

#4 Quantity distribution

from matplotlib import pyplot as plt
df['Quantity'].plot(kind='hist', bins=20, title='Quantity')
plt.gca().spines[['top', 'right',]].set_visible(False)

# 4 Sales distribution

from matplotlib import pyplot as plt
df['Sales'].plot(kind='hist', bins=20, title='Sales')
plt.gca().spines[['top', 'right',]].set_visible(False)

#4Profit vs year

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Profit', y='year', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

# Quantity vs profit

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Quantity', y='Profit', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

#4 sales vs quantity

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Sales', y='Quantity', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

#5 Corelation between various dataset
corelation = df.corr()
print(corelation)#this creates a corelation matrix
sns.heatmap(corelation)#this visualises the corelation
plt.show()

#6 Anamoly detection for sales
plt.boxplot(df['Sales'])

plt.title('Box Plot of Sales')
plt.xlabel('Sales')
plt.ylabel('Amount')


plt.show()

#6 Anamoly detection for quantity
plt.boxplot(df['Quantity'])

plt.xlabel('Quantity')
plt.ylabel('Amount')
plt.title('Box Plot of Quantity')

plt.show()

#6 Anamoly detection for profit
plt.boxplot(df['Profit'])

plt.xlabel('Profit')
plt.ylabel('Amount')
plt.title('Box Plot of Profit')

plt.show()

#7 Trend Analysis
#i
import pandas as pd
import matplotlib.pyplot as plt


df['Order Date'] = pd.to_datetime(df['Order Date'])


df['Year'] = df['Order Date'].dt.year


yearly_data = df.groupby('Year').agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()


plt.figure(figsize=(10, 6))
plt.plot(yearly_data['Year'], yearly_data['Sales'], marker='o', linestyle='-', color='b',label='sales_trend')
plt.plot(yearly_data['Year'],yearly_data['Profit'],marker='o', linestyle='-', color='black',label='profit_trend')
plt.title('Sales and profit Trend Over Years')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.grid(True)
plt.legend()
plt.show()

#we can see 7 there is a noticable variation on the trends in the year 2012 in sales

"""7
There is a noticable variation on the year 2012 in sales
\
"""

#7 Trend analysis
#ii


import pandas as pd

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Year'] = df['Order Date'].dt.year
category_sales = df.groupby(['Year', 'Category'])['Sales'].sum().unstack()
category_growth = category_sales.pct_change(axis=0) * 100
category_growth_total = category_growth.sum()
most_growing_category = category_growth_total.idxmax()
print("The category that has shown the most growth in terms of sales over the years is:", most_growing_category)

#7 Customer analysis
import pandas as pd
customer_summary = df.groupby('EmailID').agg({'Order ID': 'nunique', 'Sales': 'sum'})
customer_summary = customer_summary.sort_values(by=['Order ID', 'Sales'], ascending=False)
top_5_customers = customer_summary.head(5)
print("Top 5 Customers based on Orders Placed and Total Sales:\n", top_5_customers)

'''
Buying behaviour of customers:
we can find the customer with high engagement activity(like from the count of order id we can say that he is highly engaged)
then the total sales for each customer will be helpful for giving discounts for the customer who as sales above the fixed sales'''

#7 customer analysis

import warnings as wr
wr.filterwarnings('ignore')
df['Order Date'] = pd.to_datetime(df['Order Date'])
grouped_data = df.groupby('EmailID')
average_time_between_orders = pd.DataFrame(columns=['EmailID', 'Average Time Between Orders'])#empty dataframe

for customer, group_data in grouped_data:
    group_data = group_data.sort_values(by='Order Date')
    time_diff = group_data['Order Date'].diff().dt.days
    time_diff = time_diff.dropna()
    avg_time = time_diff.mean()
    average_time_between_orders = average_time_between_orders.append({'EmailID': customer, 'Average Time Between Orders': avg_time}, ignore_index=True)
average_time_between_orders = average_time_between_orders.sort_values(by='Average Time Between Orders', ascending=False)
average_time_between_orders.head()
print("Average Time Between Orders for Each Customer:")
average_time_between_orders.head()
#print(average_time_between_orders)

#7 strategies to be implemented to optimize the supply chain , based on the insights from sales velocity and order fulfilment data
*

"""**Qn7 strategies to be implemented to optimize the supply chain , based on the insights from sales velocity and order fulfilment data**

Demand Forecasting and Inventory Management:Utilize sales velocity data to forecast demand accurately.


Transportation Optimization:Optimize transportation routes and modes based on sales velocity and order fulfillment data to minimize transit time and transportation costs


Adopt principles :Adopt principles based for various sales velocity

**Qn 7 underlying factors will be contributing to geographic distribution of sales**

Population Density:
   Areas with higher population density often have more potential customers, leading to higher sales volume.


Demographic factors:
   Demographic factors such as age, income level, and lifestyle preferences can also impact purchasing behavior and drive sales incertain geographic regions.


Economic Conditions
   Strong local economies with higher disposable incomes tend to support greater consumer spending and higher sales.

Market Demand and Consumer Preferences:
Variations in market demand and consumer preferences across different regions influence the types of products and services that are in demand, thereby affecting sales distribution.


Consumer Preferences:
Cultural factors, lifestyle choices, and local trends can shape consumer preferences and drive sales of specific products or brands in certain geographic areas.

**Qn 7 Identification Patterns and predictors of high value customer
Certainly! Here are the key points for identifying patterns and predictors of high-value customers:**


Purchase Behavior
   - High spending per transaction.
   - Frequent purchases.
   - Consistent buying patterns.

Lifetime Value (CLV)
   - Customers with high CLV contribute significantly to revenue.
   - Predictive models estimate CLV based on historical data.

Demographic and Socioeconomic Factors
   - Higher income levels.
   - Specific age groups or geographic regions with greater purchasing power.

Engagement and Loyalty
   - Higher engagement and loyalty.
   - Participation in loyalty programs.
   - Positive feedback and interactions with the brand.
"""